#!/opt/pwn.college/python
from flask import Flask, request, make_response, redirect, session

app = Flask(__name__)
with open("/flag", "r") as fObj:
    flag = fObj.read()

@app.route("/")
def hello():
	return flag

